 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/admin/cases", type: :request do
  # Admin::Case. As you add validations to Admin::Case, be sure to
  # adjust the attributes here as well.
  let(:admin_case) { create :admin_case }

  describe "GET /index" do
    it "renders a successful response" do
      admin_case # exists
      get admin_cases_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      get admin_case_url(admin_case)
      expect(response).to be_successful
    end
  end

  describe "DELETE /destroy" do

    it "destroys the requested admin_case" do
      admin_case.review!

      delete admin_case_url(admin_case)
      expect(admin_case.reload.aasm.current_state).to equal(:closed)
    end
  end
end
